server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: notes-app
  
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: nishantkumar
    password: ""
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  security:
    user:
      name: user
      password: password

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.notes.app: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
